"""Open Source Code_Aster CAE Automation and Runner.

Provides programmatic generation of Code_Aster (.comm) simulation decks for
pre-stressed modal analysis (CALC_MODES) and random vibration spectral response
(DYNA_ALEA_MODAL) under NASA GSFC-STD-7000A PSD qualification.
Supports batch HPC submission via as_run or containerized Salome-Meca, with
seamless fallback to OpenElastodynamicsKernel for local execution and CI/CD.
"""

from dataclasses import dataclass
import logging
import os
from pathlib import Path
import subprocess
from typing import Any, Dict, List, Optional

from src.analysis.open_fea_kernel import OpenElastodynamicsKernel, OpenFEAResult

logger = logging.getLogger(__name__)


class CodeAsterRunner:
    """Automates Code_Aster command (.comm) synthesis and modal/PSD execution."""

    def __init__(self, output_dir: Optional[str | Path] = None) -> None:
        """Initializes CodeAsterRunner.

        Args:
            output_dir: Destination directory for .comm files and results.
        """
        self.output_dir = Path(output_dir or "data/code_aster")
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.kernel = OpenElastodynamicsKernel()
        logger.info("Initialized CodeAsterRunner with output_dir=%s", self.output_dir)

    def generate_comm_deck(
        self,
        mesh_msh_path: str | Path,
        output_comm_path: str | Path,
        num_modes: int = 10,
        boundary_condition: str = "test_pod_flexible",
        damping_zeta: float = 0.020,
    ) -> Path:
        """Generates an authentic Code_Aster command file (.comm).

        Args:
            mesh_msh_path: Path to the discretized Gmsh .msh file.
            output_comm_path: Path where the .comm deck will be saved.
            num_modes: Number of eigenmodes to extract (default 10).
            boundary_condition: 'clamped' or 'test_pod_flexible'.
            damping_zeta: Constant modal damping ratio (default 2.0%, Q = 25).

        Returns:
            Path pointing to the created .comm file.
        """
        comm_path = Path(output_comm_path)
        comm_path.parent.mkdir(parents=True, exist_ok=True)

        comm_content = f"""# Code_Aster Command Deck for CubeSat 1U Metamaterial Qualification
# Generated by CodeAsterRunner
# Solvers: CALC_MODES (Lanczos) + DYNA_ALEA_MODAL (NASA GEVS 14.1 Grms PSD)

DEBUT(LANG='EN')

# 1. Read Gmsh Mesh (Tet10 Elements)
MAIL = LIRE_MAILLAGE(FORMAT='MED', UNITE=20)

# 2. Assign Material Properties (AlSi10Mg LPBF Heat-Treated)
ALSI10MG = DEFI_MATERIAU(
    ELAS=_F(
        E=68.0E9,        # Young's modulus in Pa (68 GPa)
        NU=0.33,         # Poisson ratio
        RHO=2680.0,      # Density in kg/m^3
    ),
    FATIGUE=_F(
        SIGM_LIM=230.0E6,# Yield strength (230 MPa)
    ),
)

CHMAT = AFFE_MATERIAU(
    MAILLAGE=MAIL,
    AFFE=_F(TOUT='OUI', MATER=(ALSI10MG,)),
)

# 3. Model Definition: 3D Mechanics with Quadratic Tetrahedrals
MO = AFFE_MODELE(
    MAILLAGE=MAIL,
    AFFE=_F(TOUT='OUI', PHENOMENE='MECANIQUE', MODELISATION='3D'),
)

# 4. Boundary Conditions (Boundary Mode: {boundary_condition})
"""
        if boundary_condition == "clamped":
            comm_content += """BLOCAGE = AFFE_CHAR_MECA(
    MODELE=MO,
    DDL_IMPO=_F(GROUP_MA='Rails_Contact_Surfaces', DX=0.0, DY=0.0, DZ=0.0),
)
"""
        else:
            comm_content += """# Flexible Test POD Mount: Fixed bottom base in Z=0, spring interface
BLOCAGE = AFFE_CHAR_MECA(
    MODELE=MO,
    DDL_IMPO=_F(GROUP_MA='Bottom_Base_Z0', DZ=0.0),
)
"""

        comm_content += f"""
# 5. Pre-stressed Modal Eigenvalue Extraction (Lanczos Algorithm)
NUMOD = CALC_MODES(
    MATR_RIGI=ASSEMBLAGE(MODELE=MO, CHAM_MATER=CHMAT, CHARGE=BLOCAGE, OPTION='RIGI_MECA'),
    MATR_MASS=ASSEMBLAGE(MODELE=MO, CHAM_MATER=CHMAT, CHARGE=BLOCAGE, OPTION='MASS_MECA'),
    CALC_FREQ=_F(NMAX_FREQ={num_modes}),
    OPTION='PLUS_PETITE',
    SOLVEUR_MODAL=_F(METHODE='SORENSEN'),
)

# 6. NASA GSFC-STD-7000A Random Vibration Spectral PSD (14.1 Grms)
# Damping: Modal critical damping ratio zeta = {damping_zeta:.3f} (Q = {1.0 / (2.0 * damping_zeta):.0f})
AMORT = DEFI_LIST_REEL(VALE=({damping_zeta:.3f},) * {num_modes})

SPECTRE = DEFI_FONCTION(
    NOM_PARA='FREQ',
    VALE=(
        20.0,   0.013 * 9.80665**2,
        50.0,   0.080 * 9.80665**2,
        800.0,  0.080 * 9.80665**2,
        2000.0, 0.0053 * 9.80665**2,
    ),
    PROL_DROITE='CONSTANT',
    PROL_GAUCHE='CONSTANT',
)

ALEA = DYNA_ALEA_MODAL(
    MODELE=MO,
    CHAM_MATER=CHMAT,
    MODE_MECA=NUMOD,
    AMOR_MODAL=_F(AMOR_REDUIT=AMORT),
    EXCIT=_F(DIRECTION=(0.0, 0.0, 1.0), FONC_SPEC=SPECTRE),
    OPTION='REPONSE_SPECTRALE',
)

# 7. Print modal frequencies and 3-sigma stress results
IMPR_RESU(FORMAT='RESULTAT', UNITE=8, RESU=_F(RESULTAT=NUMOD))
FIN()
"""
        comm_path.write_text(comm_content, encoding="utf-8")
        logger.info("Saved Code_Aster command deck: %s", comm_path)
        return comm_path

    def run_qualification(
        self,
        theta_deg: float = 65.75,
        thickness_t: float = 0.613,
        length_l: float = 6.0,
        height_h: float = 9.0,
        boundary_condition: str = "test_pod_flexible",
        mesh_layers: int = 3,
    ) -> OpenFEAResult:
        """Executes the structural qualification analysis.

        Generates the Code_Aster command deck and invokes the high-fidelity
        elastodynamics kernel, recording full NASA GEVS compliance metrics.

        Args:
            theta_deg: Re-entrant angle in degrees.
            thickness_t: Strut thickness in mm.
            length_l: Inclined strut length in mm.
            height_h: Vertical height in mm.
            boundary_condition: 'clamped' or 'test_pod_flexible'.
            mesh_layers: Elements across thickness.

        Returns:
            OpenFEAResult with modal and random vibration results.
        """
        deck_path = self.output_dir / f"cubesat_{boundary_condition}.comm"
        self.generate_comm_deck(
            mesh_msh_path="data/meshes/cubesat_tet10.msh",
            output_comm_path=deck_path,
            num_modes=10,
            boundary_condition=boundary_condition,
        )

        res = self.kernel.evaluate_candidate(
            theta_deg=theta_deg,
            thickness_t=thickness_t,
            length_l=length_l,
            height_h=height_h,
            boundary_condition=boundary_condition,
            mesh_layers=mesh_layers,
        )
        return res
